---
- hosts: github_runner
  become: true
  vars:
    runner_version: "2.316.0"
    github_repo: "mboucheta-pro/projet-c-local"   # À adapter
  vars_files:
    - ./secrets.yml # Contient github_pat ; password : 1109
  tasks:
    - name: Obtenir un token d'enregistrement pour le runner
      uri:
        url: "https://api.github.com/repos/{{ github_repo }}/actions/runners/registration-token"
        method: POST
        headers:
          Authorization: "token {{ github_pat }}"
          Accept: "application/vnd.github.v3+json"
        status_code: 201
      register: registration_token_response

    - name: Définir le runner_token
      set_fact:
        runner_token: "{{ registration_token_response.json.token }}"

    - name: Installer les dépendances
      apt:
        name:
          - openjdk-17-jre
          - unzip
          - curl
          - tar
          - git
        state: present
        update_cache: yes

    - name: Créer le dossier du runner
      file:
        path: /opt/github-runner
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Télécharger le binaire du runner
      become_user: ubuntu
      get_url:
        url: "https://github.com/actions/runner/releases/download/v{{ runner_version }}/actions-runner-linux-x64-{{ runner_version }}.tar.gz"
        dest: /opt/github-runner/actions-runner.tar.gz

    - name: Extraire le runner
      become_user: ubuntu
      unarchive:
        src: /opt/github-runner/actions-runner.tar.gz
        dest: /opt/github-runner/
        remote_src: yes

    - name: Arrêter le service runner si déjà présent
      become_user: ubuntu
      shell: |
        if [ -f /opt/github-runner/.runner ]; then
          ./svc.sh stop || true
        fi
      args:
        chdir: /opt/github-runner

    - name: Désinstaller le service runner si déjà présent
      become_user: ubuntu
      shell: |
        if [ -f /opt/github-runner/.runner ]; then
          sudo ./svc.sh uninstall || true
        fi
      args:
        chdir: /opt/github-runner

    - name: Supprimer la configuration runner si déjà présente
      become_user: ubuntu
      shell: |
        if [ -f /opt/github-runner/.runner ]; then
          ./config.sh remove --token {{ runner_token }}
        fi
      args:
        chdir: /opt/github-runner

    - name: Supprimer le fichier service si présent
      file:
        path: /etc/systemd/system/github-runner.service
        state: absent

    - name: Supprimer le fichier .runner si présent
      become_user: ubuntu
      file:
        path: /opt/github-runner/.runner
        state: absent

    - name: Installer le runner
      become_user: ubuntu
      shell: |
        ./config.sh --url https://github.com/{{ github_repo }} --token {{ runner_token }} --unattended --labels projet-c-local --name github-runner
      args:
        chdir: /opt/github-runner

    - name: Démarrer le service runner
      become_user: ubuntu
      shell: |
        sudo ./svc.sh install
        sudo ./svc.sh start
      args:
        chdir: /opt/github-runner

    - name: Télécharger SonarScanner
      get_url:
        url: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip"
        dest: /opt/sonar-scanner.zip

    - name: Décompresser SonarScanner
      unarchive:
        src: /opt/sonar-scanner.zip
        dest: /opt/
        remote_src: yes

    - name: Créer un lien symbolique pour sonar-scanner
      file:
        src: /opt/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner
        dest: /usr/local/bin/sonar-scanner
        state: link
        force: yes

    - name: Installer Trivy (script officiel)
      shell: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin latest
      args:
        executable: /bin/bash
