---
- hosts: sonarqube
  become: true
  tasks:

    - name: Augmenter vm.max_map_count pour Elasticsearch/SonarQube
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        sysctl_set: yes
        reload: yes

    - name: Installer les dépendances de base
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG officielle de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Installer Docker et le plugin Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: S'assurer que Docker est démarré
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ajouter l'utilisateur ubuntu au groupe docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Copier le fichier docker-compose
      copy:
        src: ../files/sq-docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Créer un service systemd pour SonarQube Docker Compose
      copy:
        dest: /etc/systemd/system/sonarqube-dc.service
        content: |
          [Unit]
          Description=SonarQube via Docker Compose
          After=docker.service
          Requires=docker.service

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          User=ubuntu
          WorkingDirectory=/home/ubuntu
          ExecStart=/usr/bin/docker compose -f /home/ubuntu/docker-compose.yml up -d
          ExecStop=/usr/bin/docker compose -f /home/ubuntu/docker-compose.yml down

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Recharger systemd
      systemd:
        daemon_reload: yes

    - name: Activer et démarrer le service SonarQube Docker Compose
      systemd:
        name: sonarqube-dc
        enabled: yes
        state: started
